### ISSUE TITLE
Bug in the documentation build

### ISSUE THREAD

**Issue by ggsdc** [baobabsoluciones/cornflow#583] opened 2024-12-05 16:13 UTC
**Describe the bug**
The documentation build ahs failed as it can be seen in the following log: https://github.com/baobabsoluciones/cornflow/actions/runs/12183621233/job/33985485597

**Full log**:

```
Run cd cornflow-server
Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (24.3.1)
Ignoring greenlet: markers 'python_version >= "3.11"' don't match your environment
Collecting alembic==1.[9](https://github.com/baobabsoluciones/cornflow/actions/runs/12183621233/job/33985485597#step:4:10).2 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line 1))
  Downloading alembic-1.9.2-py3-none-any.whl.metadata (7.2 kB)
Collecting apispec<=6.2.0 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line 2))
  Downloading apispec-6.2.0-py3-none-any.whl.metadata (11 kB)
Collecting click<=8.1.3 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line 3))
  Downloading click-8.1.3-py3-none-any.whl.metadata (3.2 kB)
Collecting cornflow-client>=1.1.0 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line 4))
  Downloading cornflow_client-1.1.1-py3-none-any.whl.metadata (1.7 kB)
Collecting cryptography<=42.0.5 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line 5))
  Downloading cryptography-42.0.5-cp37-abi3-manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting disposable-email-domains>=0.0.86 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line 6))
  Downloading disposable_email_domains-0.0.111-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting Flask==2.3.2 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line 7))
  Downloading Flask-2.3.2-py3-none-any.whl.metadata (3.7 kB)
Collecting flask-apispec<=0.11.4 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line 8))
  Downloading flask_apispec-0.11.4-py2.py3-none-any.whl.metadata (4.3 kB)
Collecting Flask-Bcrypt<=1.0.1 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line 9))
  Downloading Flask_Bcrypt-1.0.1-py3-none-any.whl.metadata (2.6 kB)
Collecting Flask-Compress<=1.13 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line [10](https://github.com/baobabsoluciones/cornflow/actions/runs/12183621233/job/33985485597#step:4:11)))
  Downloading Flask_Compress-1.13-py3-none-any.whl.metadata (6.7 kB)
Collecting flask-cors>=4.0.2 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line [11](https://github.com/baobabsoluciones/cornflow/actions/runs/12183621233/job/33985485597#step:4:12)))
  Downloading Flask_Cors-5.0.0-py2.py3-none-any.whl.metadata (5.5 kB)
Collecting flask-inflate<=0.3 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line [12](https://github.com/baobabsoluciones/cornflow/actions/runs/12183621233/job/33985485597#step:4:13)))
  Downloading Flask_Inflate-0.3-py3-none-any.whl.metadata (767 bytes)
Collecting Flask-Migrate<=4.0.4 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line [13](https://github.com/baobabsoluciones/cornflow/actions/runs/12183621233/job/33985485597#step:4:14)))
  Downloading Flask_Migrate-4.0.4-py3-none-any.whl.metadata (3.1 kB)
Collecting Flask-RESTful<=0.3.9 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line [14](https://github.com/baobabsoluciones/cornflow/actions/runs/12183621233/job/33985485597#step:4:15)))
  Downloading Flask_RESTful-0.3.9-py2.py3-none-any.whl.metadata (912 bytes)
Collecting Flask-SQLAlchemy==2.5.1 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line [15](https://github.com/baobabsoluciones/cornflow/actions/runs/12183621233/job/33985485597#step:4:16)))
  Downloading Flask_SQLAlchemy-2.5.1-py2.py3-none-any.whl.metadata (3.1 kB)
Collecting gevent==23.9.1 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line [16](https://github.com/baobabsoluciones/cornflow/actions/runs/12183621233/job/33985485597#step:4:17)))
  Downloading gevent-23.9.1-cp38-cp38-manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting greenlet<=2.0.2 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line [17](https://github.com/baobabsoluciones/cornflow/actions/runs/12183621233/job/33985485597#step:4:18)))
  Downloading greenlet-2.0.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting gunicorn<=22.0.0 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line [19](https://github.com/baobabsoluciones/cornflow/actions/runs/12183621233/job/33985485597#step:4:20)))
  Downloading gunicorn-22.0.0-py3-none-any.whl.metadata (4.4 kB)
Collecting jsonpatch<=1.32 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line [20](https://github.com/baobabsoluciones/cornflow/actions/runs/12183621233/job/33985485597#step:4:21)))
  Downloading jsonpatch-1.32-py2.py3-none-any.whl.metadata (3.2 kB)
Collecting ldap3<=2.9.1 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line [21](https://github.com/baobabsoluciones/cornflow/actions/runs/12183621233/job/33985485597#step:4:22)))
  Downloading ldap3-2.9.1-py2.py3-none-any.whl.metadata (5.4 kB)
Collecting marshmallow<=3.19.0 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line [22](https://github.com/baobabsoluciones/cornflow/actions/runs/12183621233/job/33985485597#step:4:23)))
  Downloading marshmallow-3.19.0-py3-none-any.whl.metadata (7.5 kB)
Collecting PuLP<=2.9.0 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line [23](https://github.com/baobabsoluciones/cornflow/actions/runs/12183621233/job/33985485597#step:4:24)))
  Downloading PuLP-2.9.0-py3-none-any.whl.metadata (5.4 kB)
Collecting psycopg2<=2.95 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line [24](https://github.com/baobabsoluciones/cornflow/actions/runs/12183621233/job/33985485597#step:4:25)))
  Downloading psycopg2-2.9.10.tar.gz (385 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting PyJWT<=2.6.0 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line [25](https://github.com/baobabsoluciones/cornflow/actions/runs/12183621233/job/33985485597#step:4:26)))
  Downloading PyJWT-2.6.0-py3-none-any.whl.metadata (4.0 kB)
Collecting pytups>=0.86.2 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line [26](https://github.com/baobabsoluciones/cornflow/actions/runs/12183621233/job/33985485597#step:4:27)))
  Downloading pytups-0.88.1-py3-none-any.whl.metadata (3.8 kB)
Collecting requests<=2.32.3 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line [27](https://github.com/baobabsoluciones/cornflow/actions/runs/12183621233/job/33985485597#step:4:28)))
  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting SQLAlchemy==1.3.21 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line [28](https://github.com/baobabsoluciones/cornflow/actions/runs/12183621233/job/33985485597#step:4:29)))
  Downloading SQLAlchemy-1.3.21-cp38-cp38-manylinux2010_x86_64.whl.metadata (7.8 kB)
Collecting webargs<=8.2.0 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line [29](https://github.com/baobabsoluciones/cornflow/actions/runs/12183621233/job/33985485597#step:4:30)))
  Downloading webargs-8.2.0-py3-none-any.whl.metadata (8.0 kB)
Collecting Werkzeug==3.0.6 (from -r /home/runner/work/cornflow/cornflow/cornflow-server/requirements.txt (line [30](https://github.com/baobabsoluciones/cornflow/actions/runs/12183621233/job/33985485597#step:4:31)))
  Downloading werkzeug-3.0.6-py3-none-any.whl.metadata (3.7 kB)
Collecting alabaster (from -r requirements-dev.txt (line 2))
  Downloading alabaster-0.7.13-py3-none-any.whl.metadata (3.0 kB)
Collecting Babel (from -r requirements-dev.txt (line 3))
  Downloading babel-2.16.0-py3-none-any.whl.metadata (1.5 kB)
Collecting colorama (from -r requirements-dev.txt (line 4))
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting coverage (from -r requirements-dev.txt (line 5))
  Downloading coverage-7.6.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.3 kB)
Collecting docutils (from -r requirements-dev.txt (line 6))
  Downloading docutils-0.20.1-py3-none-any.whl.metadata (2.8 kB)
Collecting Flask-Testing (from -r requirements-dev.txt (line 7))
  Downloading Flask-Testing-0.8.1.tar.gz (45 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting imagesize (from -r requirements-dev.txt (line 8))
  Downloading imagesize-1.4.1-py2.py3-none-any.whl.metadata (1.5 kB)
ERROR: Ignored the following versions that require a different python version: 0.21 Requires-Python >=3.9; 0.21.1 Requires-Python >=3.9; 0.21.2 Requires-Python >=3.9; 0.21.post1 Requires-Python >=3.9; 0.21rc1 Requires-Python >=3.9; 0.7.14 Requires-Python >=3.9; 0.7.15 Requires-Python >=3.9; 0.7.16 Requires-Python >=3.9; 1.0.0 Requires-Python >=3.10; 1.16 Requires-Python >=3.9; 1.17 Requires-Python >=3.9; 2.10.0 Requires-Python >=3.9; 2.10.1 Requires-Python >=3.9; 24.10.1 Requires-Python >=3.9; 24.10.2 Requires-Python >=3.9; 24.10.3 Requires-Python >=3.9; 24.11.1 Requires-Python >=3.9; 3.1.0 Requires-Python >=3.9; 3.1.1 Requires-Python >=3.9; 3.1.2 Requires-Python >=3.9; 3.1.3 Requires-Python >=3.9; 3.23.0 Requires-Python >=3.9; 3.23.1 Requires-Python >=3.9; 6.7.0 Requires-Python >=3.9; 6.7.1 Requires-Python >=3.9; 6.8.0 Requires-Python >=3.9; 7.6.2 Requires-Python >=3.9; 7.6.3 Requires-Python >=3.9; 7.6.4 Requires-Python >=3.9; 7.6.5 Requires-Python >=3.9; 7.6.6 Requires-Python >=3.9; 7.6.7 Requires-Python >=3.9; 7.6.8 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement orloge (from versions: none)
ERROR: No matching distribution found for orloge

```

**Comment by l-prr** [comment] 2024-12-18 15:08
The issue is resolved without changes; however, generating the files results in 49 warnings.
```

loading translations [en]... done
making output directory... done
Converting `source_suffix = '.rst'` to `source_suffix = {'.rst': 'restructuredtext'}`.
[autosummary] generating autosummary for: clients/index.rst, clients/python-api.rst, deploy/access.rst, deploy/docker-compose.yml.rst, deploy/docker-stack.rst, deploy/index.rst, deploy/intro.rst, deploy/issues.rst, deploy/logs.rst, deploy/options.rst, ..., guides/jsonschema.rst, guides/testing_app.rst, guides/use_solver.rst, index.rst, main/architecture.rst, main/concepts.rst, main/index.rst, main/install.rst, main/introduction.rst, stable-rest-api-ref.rst
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
WARNING: Failed to import cornflow.endpoints.signup.
Possible hints:
* ImportError: DLL load failed while importing _bcrypt: No se encontró el proceso especificado.
* AttributeError: module 'cornflow' has no attribute 'endpoints'
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
WARNING: Failed to import cornflow.endpoints.login.
Possible hints:
* ImportError: DLL load failed while importing _bcrypt: No se encontró el proceso especificado.
* AttributeError: module 'cornflow' has no attribute 'endpoints'
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
WARNING: Failed to import cornflow.endpoints.instance.
Possible hints:
* ImportError: DLL load failed while importing _bcrypt: No se encontró el proceso especificado.
* AttributeError: module 'cornflow' has no attribute 'endpoints'
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
WARNING: Failed to import cornflow.endpoints.execution.
Possible hints:
* ImportError: DLL load failed while importing _bcrypt: No se encontró el proceso especificado.
* AttributeError: module 'cornflow' has no attribute 'endpoints'
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
WARNING: Failed to import cornflow.endpoints.user.
Possible hints:
* ImportError: DLL load failed while importing _bcrypt: No se encontró el proceso especificado.
* AttributeError: module 'cornflow' has no attribute 'endpoints'
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
WARNING: Failed to import cornflow.endpoints.case.
Possible hints:
* ImportError: DLL load failed while importing _bcrypt: No se encontró el proceso especificado.
* AttributeError: module 'cornflow' has no attribute 'endpoints'
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
WARNING: Failed to import cornflow.endpoints.dag.
Possible hints:
* ImportError: DLL load failed while importing _bcrypt: No se encontró el proceso especificado.
* AttributeError: module 'cornflow' has no attribute 'endpoints'
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 45 source files that are out of date
updating environment: [new config] 45 added, 0 changed, 0 removed
bcrypt is required to use Flask-Bcrypt_endpoints
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypts
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcryptels
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcrypt
bcrypt is required to use Flask-Bcryptdpoints
bcrypt is required to use Flask-Bcrypt
reading sources... [100%] stable-rest-api-ref
C:\Users\LuisPita\Desktop\proyectos\cornflow\docs\source\deploy\index.rst:24: WARNING: toctree contains reference to nonexisting document 'deploy/problems'
WARNING: autodoc: failed to import module 'endpoints.dag' from module 'cornflow'; the following exception was raised:
DLL load failed while importing _bcrypt: No se encontró el proceso especificado.
C:\Users\LuisPita\Desktop\proyectos\cornflow\libs\client\cornflow_client\core\instance_solution.py:docstring of cornflow_client.core.instance_solution.InstanceSolutionCore.from_element_or_list_to_dict:4: ERROR: Unexpected indentation.
C:\Users\LuisPita\Desktop\proyectos\cornflow\libs\client\cornflow_client\core\experiment.py:docstring of cornflow_client.core.experiment.ExperimentCore.get_solver_config:3: ERROR: Unexpected indentation.
C:\Users\LuisPita\Desktop\proyectos\cornflow\libs\client\cornflow_client\core\experiment.py:docstring of cornflow_client.core.experiment.ExperimentCore.get_solver_config:4: WARNING: Block quote ends without a blank line; unexpected unindent.
C:\Users\LuisPita\Desktop\proyectos\cornflow\libs\client\cornflow_client\core\experiment.py:docstring of cornflow_client.core.experiment.ExperimentCore.get_solver_config:10: WARNING: Definition list ends without a blank line; unexpected unindent.
C:\Users\LuisPita\Desktop\proyectos\cornflow\libs\client\cornflow_client\schema\tools.py:docstring of cornflow_client.schema.tools.add_details:5: ERROR: Unexpected indentation.
C:\Users\LuisPita\Desktop\proyectos\cornflow\libs\client\cornflow_client\schema\tools.py:docstring of cornflow_client.schema.tools.add_details:8: WARNING: Definition list ends without a blank line; unexpected unindent.
WARNING: autodoc: failed to import module 'endpoints.signup' from module 'cornflow'; the following exception was raised:
DLL load failed while importing _bcrypt: No se encontró el proceso especificado.
WARNING: autodoc: failed to import module 'endpoints.login' from module 'cornflow'; the following exception was raised:
DLL load failed while importing _bcrypt: No se encontró el proceso especificado.
WARNING: autodoc: failed to import module 'endpoints.instance' from module 'cornflow'; the following exception was raised:
DLL load failed while importing _bcrypt: No se encontró el proceso especificado.
WARNING: autodoc: failed to import module 'endpoints.execution' from module 'cornflow'; the following exception was raised:
DLL load failed while importing _bcrypt: No se encontró el proceso especificado.
WARNING: autodoc: failed to import module 'endpoints.user' from module 'cornflow'; the following exception was raised:
DLL load failed while importing _bcrypt: No se encontró el proceso especificado.
WARNING: autodoc: failed to import class 'models.meta_models.EmptyBaseModel' from module 'cornflow'; the following exception was raised:
DLL load failed while importing _bcrypt: No se encontró el proceso especificado.
WARNING: autodoc: failed to import class 'models.meta_models.TraceAttributesModel' from module 'cornflow'; the following exception was raised:
DLL load failed while importing _bcrypt: No se encontró el proceso especificado.
WARNING: autodoc: failed to import class 'models.base_data_model.BaseDataModel' from module 'cornflow'; the following exception was raised:
DLL load failed while importing _bcrypt: No se encontró el proceso especificado.
WARNING: autodoc: failed to import class 'models.InstanceModel' from module 'cornflow'; the following exception was raised:
DLL load failed while importing _bcrypt: No se encontró el proceso especificado.
WARNING: autodoc: failed to import class 'models.ExecutionModel' from module 'cornflow'; the following exception was raised:
DLL load failed while importing _bcrypt: No se encontró el proceso especificado.
WARNING: autodoc: failed to import class 'models.CaseModel' from module 'cornflow'; the following exception was raised:
DLL load failed while importing _bcrypt: No se encontró el proceso especificado.
WARNING: autodoc: failed to import class 'models.UserModel' from module 'cornflow'; the following exception was raised:
DLL load failed while importing _bcrypt: No se encontró el proceso especificado.
WARNING: autodoc: failed to import module 'endpoints.case' from module 'cornflow'; the following exception was raised:
DLL load failed while importing _bcrypt: No se encontró el proceso especificado.
C:\Users\LuisPita\Desktop\proyectos\cornflow\cornflow-dags\DAG\knapsack\README.rst:16: WARNING: duplicate label decision, other instance in C:\Users\LuisPita\Desktop\proyectos\cornflow\docs\source\examples/graph_coloring.rst
C:\Users\LuisPita\Desktop\proyectos\cornflow\cornflow-dags\DAG\knapsack\README.rst:21: WARNING: duplicate label parameters, other instance in C:\Users\LuisPita\Desktop\proyectos\cornflow\docs\source\examples/graph_coloring.rst
../cornflow-dags/DAG/roadef/README.rst:70: WARNING: Line block ends without a blank line.
C:\Users\LuisPita\Desktop\proyectos\cornflow\cornflow-dags\DAG\rostering\README.rst:14: WARNING: duplicate label decision, other instance in C:\Users\LuisPita\Desktop\proyectos\cornflow\docs\source\examples/knapsack.rst
C:\Users\LuisPita\Desktop\proyectos\cornflow\cornflow-dags\DAG\rostering\README.rst:38: WARNING: duplicate label parameters, other instance in C:\Users\LuisPita\Desktop\proyectos\cornflow\docs\source\examples/knapsack.rst
C:\Users\LuisPita\Desktop\proyectos\cornflow\cornflow-dags\DAG\tsp\README.rst:15: WARNING: duplicate label decision, other instance in C:\Users\LuisPita\Desktop\proyectos\cornflow\docs\source\examples/rostering.rst
C:\Users\LuisPita\Desktop\proyectos\cornflow\cornflow-dags\DAG\tsp\README.rst:20: WARNING: duplicate label parameters, other instance in C:\Users\LuisPita\Desktop\proyectos\cornflow\docs\source\examples/rostering.rst
../cornflow-dags/DAG/vrp/README.rst:8: WARNING: Inline literal start-string without end-string.
C:\Users\LuisPita\Desktop\proyectos\cornflow\cornflow-dags\DAG\vrp\README.rst:18: WARNING: duplicate label decision, other instance in C:\Users\LuisPita\Desktop\proyectos\cornflow\docs\source\examples/tsp.rst
C:\Users\LuisPita\Desktop\proyectos\cornflow\cornflow-dags\DAG\vrp\README.rst:23: WARNING: duplicate label parameters, other instance in C:\Users\LuisPita\Desktop\proyectos\cornflow\docs\source\examples/tsp.rst
C:\Users\LuisPita\Desktop\proyectos\cornflow\docs\source\guides/coding_style.rst:263: WARNING: Explicit markup ends without a blank line; unexpected unindent.
C:\Users\LuisPita\Desktop\proyectos\cornflow\docs\source\guides/coding_style.rst:273: WARNING: Explicit markup ends without a blank line; unexpected unindent.
C:\Users\LuisPita\Desktop\proyectos\cornflow\docs\source\guides/coding_style.rst:275: ERROR: Error in "code-block" directive:
maximum 1 argument(s) allowed, 12 supplied.

.. code-block:: python
    def get_real_end_timeslot(self) -> SuperDict:
        return self._get_property("production_scheduling", "end_timeslot").vapply(
            lambda v: get_date_time_from_string(v)
        )
C:\Users\LuisPita\Desktop\proyectos\cornflow\docs\source\guides\deploy_solver_new.rst:89: WARNING: duplicate label schema_checks, other instance in C:\Users\LuisPita\Desktop\proyectos\cornflow\docs\source\guides/deploy_solver_new.rst
C:\Users\LuisPita\Desktop\proyectos\cornflow\docs\source\main\install.rst:5: WARNING: duplicate label requirements, other instance in C:\Users\LuisPita\Desktop\proyectos\cornflow\docs\source\guides/deploy_solver_new.rst
C:\Users\LuisPita\Desktop\proyectos\cornflow\docs\source\main\introduction.rst:52: WARNING: duplicate label components, other instance in C:\Users\LuisPita\Desktop\proyectos\cornflow\docs\source\main/architecture.rst
looking for now-outdated files... none found
pickling environment... done
checking consistency... C:\Users\LuisPita\Desktop\proyectos\cornflow\docs\source\deploy/issues.rst: WARNING: document isn't included in any toctree
copying assets... 
copying static files... Copying the source path C:\Users\LuisPita\Desktop\proyectos\cornflow\venv\Lib\site-packages\shibuya\theme\shibuya\static/pygments.css to build\html\_static/pygments.css will overwrite data, as a file already exists at the destination path and the content does not match.
done
copying extra files... done
copying assets: done
writing output... [100%] stable-rest-api-ref
generating indices... genindex py-modindex done
writing additional pages... search done
copying images... [100%] _static/concepts_tsp2.png
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 45 warnings.

The HTML pages are in build\html.
``` 

Screenshot with the html files created:
![Image](https://github.com/user-attachments/assets/2b50b5fd-8f89-418c-8ddd-70de184e14ea)

**Closed** 2024-12-23 11:07 UTC
Labels: bug, documentation, good first issue
